name: kaggle
dependencies:
  - python>=3.6
  - tqdm
  - matplotlib
  - scipy
  - numpy
  - pandas
  - dask
  - distributed
  - bokeh
  - pip
  - notebook
  - ipywidgets
  - jupyter_contrib_nbextensions
  - scikit-learn
  - seaborn
  - sqlite3
  - requests
