#!/bin/bash
#===============================================================
# Uses relative directory paths and assumes there is a data
# subfolder in the root of the repo and a raw folder inside that
#
# Creates stores table
# Imports all store data into sqlite db

DATA=../data/extra
DB=datasci.db

# Create stores table
sqlite3 $DB "CREATE TABLE social
(
	postcode	smallint
,	advantage_score	smallint
,	disadvantage_score	smallint
,	economic_score	smallint
,	occupation_score	smallint
,   population smallint
)"

sqlite3 -separator $',' $DB ".import $DATA/socio_mapping.csv social"
