#!/bin/bash
#===============================================================
# Uses relative directory paths and assumes there is a data
# subfolder in the root of the repo and a raw folder inside that
#
#Uses file pc_state_lat_lon.txt that was generated by Griff's shell script:
#
# wget http://download.geonames.org/export/zip/AU.zip
# unzip AU.zip
# cut -d $'\t' -f 2,5,10,11 AU.txt | sort -n > pc_state_lat_lon.txt
#
#Cuts out duplicate postcodes - assigning average lat lon coordinates to these.


DATA=../data/Lookups
DB=../data/medi.db

sqlite3 $DB "DROP TABLE IF EXISTS postcodes_geo"

# Create stores table
sqlite3 $DB "CREATE TABLE postcodes_geo
(
  postcode varchar(5) default NULL,
  state varchar(4) default NULL,
  latitude decimal(6,3) default NULL,
  longitude decimal(6,3) default NULL
)"

sqlite3 -separator $'\t' $DB ".import $DATA/pc_state_lat_lon.txt postcodes_geo"

sqlite3 $DB < cut_postcodes.sql

